In [1]:
import numpy as np

In [2]:
def elementary_decomposition(A):
    A = np.array(A, dtype=float)
    n = A.shape[0]
    
    # Store inverses of elementary matrices
    elementary_matrices = []
    
    # Step 1: Scale first row
    if A[0,0] != 1:
        E1_inv = np.eye(n)
        E1_inv[0,0] = A[0,0]
        elementary_matrices.append(E1_inv)
        A[0] = A[0] / A[0,0]
    
    # Step 2: Eliminate below pivot
    if A[1,0] != 0:
        factor = A[1,0]
        E2_inv = np.eye(n)
        E2_inv[1,0] = factor
        elementary_matrices.append(E2_inv)
        A[1] = A[1] - factor * A[0]
    
    # Step 3: Scale second row
    if A[1,1] != 1:
        E3_inv = np.eye(n)
        E3_inv[1,1] = A[1,1]
        elementary_matrices.append(E3_inv)
        A[1] = A[1] / A[1,1]
    
    # Step 4: Eliminate above pivot
    if A[0,1] != 0:
        factor = A[0,1]
        E4_inv = np.eye(n)
        E4_inv[0,1] = factor
        elementary_matrices.append(E4_inv)
        A[0] = A[0] - factor * A[1]
    
    return elementary_matrices

In [3]:
# Example matrix
A = [[4, 3],[2, 1]]
matrices = elementary_decomposition(A)

In [4]:
# Verify the product
product = np.eye(2)
for M in matrices:
    product = product @ M

In [5]:
print("Elementary matrices (in order):")
for i, M in enumerate(matrices, start=1):
    print(f"E{i}^-1:\n{M}\n")

print("Product of elementary matrices:")
print(product)

Elementary matrices (in order):
E1^-1:
[[4. 0.]
 [0. 1.]]

E2^-1:
[[1. 0.]
 [2. 1.]]

E3^-1:
[[ 1.   0. ]
 [ 0.  -0.5]]

E4^-1:
[[1.   0.75]
 [0.   1.  ]]

Product of elementary matrices:
[[4. 3.]
 [2. 1.]]
