## Name: Tirtham Bafna
## RegNo: 240957022
## CLA Lab1: Basics
## Date: 26/07/2025

In [ ]:
import numpy as np    
import time

In [3]:
# Creating a matrix
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print("Matrix A:\n", A)

# Printing the order (dimensions) of the matrix
print("Order (dimensions) of A: ",A.shape)
print("Number of rows in A: ",A.shape[0])#rows
print("Number of columns in A: ",A.shape[1])#columns

Matrix A:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Order (dimensions) of A:  (4, 3)
Number of rows in A:  4
Number of columns in A:  3


In [7]:
def dot_fn(a, b): # Computing the dot product of two vectors using a for loop
    if a.shape[0] != b.shape[0]:
        print("Enter vectors of the same size")
        return
    sum = 0
    for i in range(a.shape[0]):
        sum +=a[i] * b[i]
    return sum

In [8]:
# Dot product of two vectors using dot_fn
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
c = dot_fn(a, b)
print("dot_fn(a, b) = ",c)

dot_fn(a, b) =  24


In [9]:
# Dot product of two vectors using numpy dot function
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
d1 = np.dot(a, b)
print("np.dot(a, b) = ",d1) 
d2 = np.dot(b, a)
print("np.dot(b, a) = ",d2) 

np.dot(a, b) =  24
np.dot(b, a) =  24


In [15]:
size = 10**7 # Length of the vectors

# Set random seed for reproducibility
np.random.seed(1)

a = np.random.randint(-10, 11, size)  # very large arrays
b = np.random.randint(-10, 11, size)
#print(a)
#print(b)


print("Shape of a: ",a.shape)
print("Shape of b: ",b.shape)

start_time = time.time()  # capture start time
c = np.dot(a, b)
end_time = time.time()  # capture end time
dot_time = end_time - start_time

print("np.dot(a, b) = ",c)
print("Vectorized version duration: ", dot_time,"sec")

start_time = time.time()  # capture start time
c = dot_fn(a,b)
end_time = time.time()  # capture end time
loop_time = end_time - start_time

print("dot_fn(a, b) = ",c)
print("Loop version duration: ", loop_time,"sec")


speedup = loop_time / dot_time
print(f"\nVectorized code is {speedup:.2f} times faster than the for loop code.")

Shape of a:  (10000000,)
Shape of b:  (10000000,)
np.dot(a, b) =  -39561
Vectorized version duration:  0.015825271606445312 sec
dot_fn(a, b) =  -39561
Loop version duration:  2.464677333831787 sec

Vectorized code is 155.74 times faster than the for loop code.


In [16]:
# Numpy dot function can also be used for matrix multiplication

B = np.array([[1, 2], [3, 1]])
C = np.array([[4, 1], [2, 2]])

ProdBC = np.dot(B,C)
ProdCB = np.dot(C,B)

print("BC = \n",ProdBC)
print("CB = \n",ProdCB)

BC = 
 [[ 8  5]
 [14  5]]
CB = 
 [[7 9]
 [8 6]]


In [17]:
i = np.array([[0, -1], [1, 0]])    # Matrix corresponding to complex number i

print(np.dot(i, i))

[[-1  0]
 [ 0 -1]]


In [18]:
i = np.array([[0, -1], [1, 0]]) 
v = np.array([-1, 0])

print(np.dot(i, v))

[ 0 -1]



EXERCISE: 

Write a code to rotate the vector (0, -1) by 90 degrees. Write your interpretation.

In [27]:
v=np.array([0,-1])

v1=np.dot(i,v)
print(v1,"Rotation by 90 degrees anticlockwise")
v2=np.dot(i,v1)
print(v2,"Rotation by 90 degrees anticlockwise")
v3=np.dot(i,v2)
print(v3,"Rotation by 90 degrees anticlockwise\nFinal Original Vector reached")

[1 0] Rotation by 90 degrees anticlockwise
[0 1] Rotation by 90 degrees anticlockwise
[-1  0] Rotation by 90 degrees anticlockwise
Final Original Vector reached


### On considering a 2d space with real numbers on x axis and complex numbers on y axis, we can think of [0,-1] as (0,-i).
### Consider a vector stretching to the point (0,-1); when we rotate the vector by 90 degrees anticlockwise the vector will lie on x axis as (0,1)
### Further rotation ny 90 degrees will lead to the vector lying on +y axis as (0,1)
### The third and final rotation will transform the vector back to the original (-1,0)
### These four points are the fourth roots of unity as they form a circle of r=1 in complex coordinates as z=r cos (e^(i.theta))